site_name: VIAME-Web-NOAA-GCP
site_url: https://us-amlr.github.io/viame-web-noaa-gcp
site_author: Sam Woodman

repo_url: https://github.com/us-amlr/viame-web-noaa-gcp

theme:
  name: material
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

extra:
  social:
    - icon: fontawesome/solid/building
      link: https://www.commerce.gov/
    - icon: fontawesome/solid/cloud
      link: https://www.noaa.gov
    - icon: fontawesome/solid/fish-fins
      link: https://www.fisheries.noaa.gov/

nav:
  - Home: index.md
  - Deployment Guide: 
    - Deployment: 
      - General: deployment-general.md
      - Scenarios:
        - Default: deployment-default.md
        - Split Services: deployment-split.md
    - Accessing VIAME-Web: deployment-access.md
    - Network Changes: network-changes.md
    - Qwiklabs: qwiklabs.md
  - Administrator Guide:
    - General: admin-general.md
    - Cloud Storage Integration: admin-storage.md
    - Server Migration: admin-server-migration.md
    - Automatically Start Services: admin-docker-autostart.md
  - Support: support.md
