site_name: VIAME-Web-NOAA-GCP
site_url: https://us-amlr.github.io/viame-web-noaa-gcp
site_author: Sam Woodman

repo_url: https://github.com/us-amlr/viame-web-noaa-gcp

theme:
  name: material
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# extra_css: [extra.css]

nav:
  - Home: index.md
  - Deployment Guide: 
    - Deployment: 
      - General: deployment-general.md
      - Scenarios:
        - Default: deployment-default.md
        - Split Services: deployment-split.md
    - Accessing VIAME-Web: deployment-access.md
    - Network Changes: network-changes.md
  - Administrator Guide:
    - General: admin-general.md
    - Cloud Storage Integration: admin-storage.md
    - Server Migration: admin-server-migration.md
  - Support: support.md
