site_name: VIAME-Web-todo
site_url: https://smwoodman.github.io/viame-web-fisheries-cloud
site_author: Sam Woodman

repo_url: https://github.com/smwoodman/viame-web-fisheries-cloud

theme:
  name: material
  highlightjs: true
#   palette:
#     primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# extra_css: [extra.css]

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/kitware/dive
#     - icon: fontawesome/brands/docker
#       link: https://hub.docker.com/r/kitware/viame-web
#     - icon: fontawesome/brands/discourse
#       link: https://discourse.kitware.com/c/viame-dive/17
#   analytics:
#     provider: google
#     property: UA-6042509-43

nav:
  - General: 
    - Home: index.md
    - Network Changes: network-changes.md
  - Deployment: 
    - Overview: deployment-overview.md
    - Deployment: 
      - General: deployment-general.md
      - Scenarios:
        - Default: deployment-default.md
        - Split Services: deployment-split.md
    - Access VIAME-Web: deployment-access.md
  - Support: support.md
